apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-jenkins-pipeline-deploy-web.fullname" . }}
  labels:
    {{- include "demo-jenkins-pipeline-deploy-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-jenkins-pipeline-deploy-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseTime: {{ now | quote }}
      labels:
        {{- include "demo-jenkins-pipeline-deploy-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo-jenkins-pipeline-deploy-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - java
            - -XX:MaxRAMPercentage=70
            - -XX:+UseShenandoahGC
            - -XX:+UseStringDeduplication
            - -XX:+HeapDumpOnOutOfMemoryError
            - -XX:HeapDumpPath=/data/log_files
            - -jar
            - /app/app.jar
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default "/actuator/health/liveness" .Values.livenessProbe.path }}
              port: http
              {{- with .Values.livenessProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ default 5 .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ default 10 .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ default "/actuator/health/readiness" .Values.readinessProbe.path }}
              port: http
              {{- with .Values.readinessProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ default 5 .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ default 10 .Values.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.spring.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.spring.datasource.secret }}
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.spring.datasource.secret }}
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.spring.kafka.bootstrapServers }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
